"""db_criar_cadastro

Revision ID: 658ccb828f97
Revises: df1c51eca122
Create Date: 2023-08-16 11:39:05.747287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '658ccb828f97'
down_revision = 'df1c51eca122'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cadastro_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=40), nullable=False),
    sa.Column('sobrenome', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('senha', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cadastro_model')
    # ### end Alembic commands ###
